[project]
name = "url-shortner-lite"
version = "0.1.0"
description = "A lightweight, self-hosted URL shortener with admin panel, analytics, and password-protected links."
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "aniso8601==9.0.1",
    "apscheduler==3.11.1",
    "blinker==1.9.0",
    "click==8.1.7",
    "dnspython==2.7.0",
    "flask==3.1.0",
    "flask-restful==0.3.10",
    "gunicorn==23.0.0",
    "itsdangerous==2.2.0",
    "jinja2==3.1.4",
    "markupsafe==3.0.2",
    "packaging==24.2",
    "pillow==11.3.0",
    "pymongo==4.6.0",
    "python-dotenv==1.0.1",
    "pytz==2024.2",
    "qrcode==8.2",
    "requests==2.32.3",
    "six==1.16.0",
    "tzlocal==5.3.1",
    "werkzeug==3.1.3",
]
